TechnologyEnhancedLearning/nhse-tel-frontend

app/components/tel/readme.md
packages/components/tel/readme.md

Created "tel" folder to host the bespoke components. This was located in 2 locations:
/add/components/
/packages/components/

Create tel folder for components

---

app/_templates/layout.njk
app/_templates/page.njk
app/pages/install.njk

Update references to NHS.UK frontend to NHS.UK frontend TEL

---

.github/PULL_REQUEST_TEMPLATE.md

Update paths to point to content in this repo instead of original repo

Update paths to testing and coding standards

---

package.json

Some updates to package.json to use correct name and also fix paths to point to this repo and not the original.
Version has been updated to 0.0.1 ready for the first release.

Update paths, version and description

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

Simple text update to add "TEL" to name

Update name to NHS.UK frontend TEL

---

.gitignore
README.md

Readme.md contents has been updated as follows:
- removed Guidance section
- changed any reference to NHS.UK frontend to NHS.UK frontend TEL
- removed development environment section
- updated Get in touch contact info

Feature/td 5062 update readme.md

---

.github/workflows/pull-request.yml
tests/linters/.eslintrc.js

Update prettier rule to warn instead of error in case of code non-conformity

Update prettier rule to warn instead of error in case of code non-conformity

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Updated the pull request template to be more in line with the template used on other TEL repos. Note I have not included any reference to JIRA as my understanding everything is in GitHub

Updated to be more in line with other TEL PR templates

---

DotnetViewComponents/ViewComponents/PaginationViewComponent.cs
DotnetViewComponents/ViewModels/PaginationViewModel.cs
DotnetViewComponents/Views/Shared/Components/Pagination/Default.cshtml

Create Pagination View, ViewComponent and Model
-----
I have:
Either:
Or:

Create Pagination View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/TableViewComponent.cs
DotnetViewComponents/ViewModels/TableViewModel.cs
DotnetViewComponents/Views/Shared/Components/Table/Default.cshtml

Create Table View, ViewComponent and Model
-----
I have:
Either:
Or:

Create Table View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/ImageViewComponent.cs
DotnetViewComponents/ViewModels/ImageViewModel.cs
DotnetViewComponents/Views/Shared/Components/Image/Default.cshtml

Create Image View, ViewComponent and Model
-----
I have:
Either:
Or:

Create Image View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/CharacterCountViewComponent.cs
DotnetViewComponents/ViewModels/CharacterCountViewModel.cs
DotnetViewComponents/Views/Shared/Components/CharacterCount/Default.cshtml

Create CharacterCount View, VIewComponent and Model.
-----
I have:
Either:
Or:

Create CharacterCount View, ViewComponent and Model.

---

DotnetViewComponents/ViewComponents/TagViewComponent.cs
DotnetViewComponents/ViewModels/TagViewModel.cs
DotnetViewComponents/Views/Shared/Components/Tag/Default.cshtml

Create Tag View, ViewComponent and Model
-----
I have:
Either:
Or:

Create Tag View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/FooterViewComponent.cs
DotnetViewComponents/ViewModels/FooterItemViewModel.cs
DotnetViewComponents/ViewModels/FooterViewModel.cs
DotnetViewComponents/Views/Shared/Components/Footer/Default.cshtml

Create Footer View, ViewComponent and Model
-----
I have:
Either:
Or:

Create Footer View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/ContentsListViewComponent.cs
DotnetViewComponents/ViewModels/ContentListItemViewModel.cs
DotnetViewComponents/ViewModels/ContentsListViewModel.cs
DotnetViewComponents/Views/Shared/Components/ContentsList/Default.cshtml

Create ContentsList View, ViewComponent and Model
-----
I have:
Either:
Or:

Create ContentsList View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/DoDontListViewComponent.cs
DotnetViewComponents/ViewModels/DoDontListViewModel.cs
DotnetViewComponents/Views/Shared/Components/DoDontList/Default.cshtml

Create DoDontList View, ViewComponent and Model
-----
I have:
Either:
Or:

Create DoDontList View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/SkipLinkViewComponent.cs
DotnetViewComponents/ViewModels/SkipLinkViewModel.cs
DotnetViewComponents/Views/Shared/Components/SkipLink/Default.cshtml

Create SkipLink View, ViewComponent and Model
-----
I have:
Either:
Or:

Create SkipLink View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/BreadcrumbsViewComponent.cs
DotnetViewComponents/ViewModels/BreadcrumbsViewModel.cs
DotnetViewComponents/Views/Shared/Components/Breadcrumbs/Default.cshtml

Create Breadcrumbs View, ViewComponent and Model
Desktop view
Mobile view
-----
I have:
Either:
Or:

Create Breadcrumbs View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/DetailsViewComponent.cs
DotnetViewComponents/ViewModels/DetailsViewModel.cs
DotnetViewComponents/Views/Shared/Components/Details/Default.cshtml

Create Details View, ViewComponent and Model
-----
I have:
Either:
Or:

Create Details View, ViewComponent and Model

---

DotnetViewComponents/ViewComponents/CardViewComponent.cs
DotnetViewComponents/ViewModels/CardViewModel.cs
DotnetViewComponents/Views/Shared/Components/Card/Default.cshtml

Create Card View, VIew Component and Model.
-----
I have:
Either:
Or:

Create Card View, VIew Component and Model.
